In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('boss.csv')

In [8]:
df

,PM2.5,PM10,NO,NO2,NOx,NH3,SO2,CO,Ozone,Benzene,Toluene,Eth-Benzene,MP-Xylene,RH,WS,WD,SR,BP,VWS,AT
0,16.4,56.1,3.1,8.3,11.4,26.90,2.10,0.53,20.18,0.86,1.36,0.28,0.14,99.75,1.01,104.02,9.1,998.9,0.02,27.27
1,16.4,56.1,3.1,8.1,11.1,26.90,1.90,0.52,20.18,0.98,1.37,0.26,0.12,99.75,0.44,112.27,8.7,998.8,0.03,27.24
2,16.4,56.1,3.1,7.5,10.6,26.80,2.20,0.51,19.83,0.84,1.30,0.23,0.11,99.75,0.72,110.27,9.5,998.8,0.03,27.23
3,13.0,57.1,3.0,7.1,10.1,26.50,2.00,0.50,19.84,0.65,1.34,0.22,0.09,99.75,0.55,110.99,8.6,998.7,0.03,27.18
4,11.5,57.6,3.0,6.2,9.3,26.50,2.00,0.50,18.66,0.61,1.21,0.19,0.08,99.75,0.48,107.01,8.3,998.6,0.02,27.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22871,6.9,36.8,4.9,11.0,15.9,25.57,2.45,0.41,24.61,2.38,2.01,1.74,1.30,99.76,1.16,88.41,59.2,996.3,0.02,24.33
22872,6.9,36.8,4.9,11.8,16.7,25.70,2.32,0.43,22.90,2.20,2.07,1.63,1.10,99.76,1.00,94.66,63.9,997.1,0.01,24.39
22873,6.9,36.8,5.0,11.9,16.8,25.75,2.24,0.42,22.20,2.51,2.16,1.76,1.27,99.76,0.92,98.80,68.6,996.8,0.02,24.37
22874,6.8,36.7,4.9,11.4,16.3,25.67,2.15,0.42,22.53,2.25,2.10,1.64,1.22,99.76,0.46,91.88,64.1,996.8,0.02,24.35
22875,6.7,36.7,4.9,10.2,15.1,25.65,2.14,0.38,23.99,2.61,2.00,1.86,1.10,99.76,0.98,92.40,60.9,996.7,0.01,24.28

In [9]:
df.isnull().sum()

PM2.5          0
PM10           0
NO             0
NO2            0
NOx            0
NH3            0
SO2            0
CO             0
Ozone          0
Benzene        0
Toluene        0
Eth-Benzene    0
MP-Xylene      0
RH             0
WS             0
WD             0
SR             0
BP             0
VWS            0
AT             0
dtype: int64

In [10]:
import seaborn as sns

In [31]:
X = df.iloc[:,2:]
y = df.iloc[:,0:2]

In [32]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y,test_size=0.2,random_state=2)

In [38]:
yt1=y_train.iloc[:,0:1]
yt2=y_train.iloc[:,1:]
y1=y_test.iloc[:,0:1]
y2=y_test.iloc[:,1:]

In [37]:
y_train

       PM2.5   PM10
20578   20.9   41.1
21708   20.8   41.2
9188    76.4  136.4
20245   27.7   77.9
9583   132.9  198.6
...      ...    ...
1099     5.6   16.7
18898   10.6   27.0
11798   58.5  120.2
6637    57.0   95.4
2575     6.2   15.5

[18300 rows x 2 columns]

In [39]:
from sklearn.tree import DecisionTreeRegressor

In [40]:
regressor1 = DecisionTreeRegressor(random_state=0)

In [26]:
regressor2 = DecisionTreeRegressor(random_state=0)

In [41]:
regressor1.fit(X_train, yt1)

DecisionTreeRegressor(random_state=0)

In [42]:
pred = regressor1.predict(X_test)

In [46]:
from sklearn.metrics import r2_score

In [47]:
r2_score(pred, y1)

0.9543881190414136